Display QPI image data
DC-analysis/DCscope pull request #146
Opened 2023-10-31 13:55 UTC by PinkShnack

As described in (create issue)  I want to see qpi data non-scalar features in shapeout2.

2023-10-31 13:59 UTC, PinkShnack commented
Progress so-far:

I just need to generalise the methods and then this should be ready for review. (I'm sure I'll need some tests also)

![view_normal](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/43960046/44ed155d-ee06-4ca9-bdfd-eeecb628dbf9)
![view_poly](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/43960046/207bcffb-2961-4535-a622-8545f2901ba3)
![view_zoom](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/43960046/4a6594dd-2c41-491f-ab5f-f5841db85400)

2023-10-31 16:05 UTC, PinkShnack reviewed
@paulmueller when you get a chance, pleae have a look at the changes :)

I tested that it works on normal rtdc files, and on rtdc files with qpi data.

Perhaps I need to add some tests?

2023-10-31 16:05 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +
I generalised this a bit. Check if there is anything more to do :)

2023-10-31 16:05 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +            self.imageView_image_poly.hide()
We can hide first and have that as default, and then call `.show()` if the image is available (see below)

2023-10-31 16:05 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +                            self.imageView_image_poly.show()
I don't like that this is sliiiightly different than `show_event`. I guess I could add a groupBox for the poly images?

2023-10-31 16:05 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +                        self.imageView_image.setImage(cellimg, **imkw)
These if statements also annoy me a bit. Is there a way to access the QT attributes via string definitions?

2023-10-31 16:38 UTC, paulmueller requested changes
The main issue that I see is that the current way contours are plotted is outdated and also does not work with phase data (changing pixels in an RGB image). So as far as I can see, there is no way around rewriting displaying the contour for phase and amplitude data.

Also, I believe there should be some way of setting the range for (at least) phase values. And phase values should always be centered at zero with the corresponding colormap showing white or no color. "coolwarm" from matplotlib is a good way of displaying phase, but you would have to copy-paste it to work with pyqtgraph, because I think it is not (yet) in pyqtgraph. "viridis" got ported to pyqtgraph, so it should be straight-forward.

2023-10-31 16:38 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +
I would not convert the float32 images to uint8. This could make things look really ugly (the kind of artifacts you see in .gif images) and pyqtgraph should support showing float32 images. Also, for the phase images you would like to use the diverging colormap [coolwarm](https://matplotlib.org/stable/users/explain/colors/colormaps.html#diverging) (needs to be ported to ShapeOut without adding the matplotlib dependency). So ideally, you have a background phase of 0 and then a symmetric colormap with positive (red) and negative (blue) phase delay.

2023-10-31 16:38 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
In the future, we might want to change how we compute/display the contour, i.e. we are planning to use non-discrete contours (@SaraKaliman). So it might make sense to implement two functions `add_contour_to_image` (for "image" data) and `draw_contour_on_plot` (for float32 qpi data) which could then also be used later for non-discrete contours.

2023-10-31 16:38 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +                            self.imageView_image_poly.show()
Maybe there should be a separate class entirely that handles image plotting? Generalization is not easy due to the different data types and requirements for visualization.

2023-10-31 16:38 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +                        self.imageView_image.setImage(cellimg, **imkw)
You could generalize it with dictionaries defined in `__init__`:
```python
self.img_info = {
    "image": [self.imageView_image, "gray"],
    "qpi_pha": [self.imageView_image_pha. "coolwarm"],
etc...
}
 
```

2023-10-31 16:38 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.ui
> +       <number>2</number>
keep 0 the default

2023-11-02 15:14 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.ui
> +       <number>2</number>
No idea how that changed. QT seems to change random stuff

2023-11-02 15:17 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
Practically I want to use shapeout to visualise the image data so Kyoo can look at the data in one place. For that, what I have built right now is enough. The colormaps and contour issues will just hold that up. Could we put all that in a separate PR?

2023-11-03 16:56 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.ui
> +       <number>2</number>
If you click on the tabs in QtDesigner, it sets this tab as default.

2023-11-03 17:00 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
If it is just for Kyoo, then you could just create a custom installer for him:

```
cd build_recipes
pip install -r win_build_requirements.txt
pyinstaller -y --log-level=WARN win_ShapeOut2.spec
```

2023-11-03 17:02 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
I would not like to merge an incomplete feature. Moreover, the grayscale colormap leads to ambiguities. This should not be used by the general crowd.

2023-11-03 17:18 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
If you think it isn't a complete feature then I understand. **I'll try to implement the colorbar etc soon.**

Thanks for the custom executable, much better... I was just gonna do the dev version. :)

2023-11-17 18:48 UTC, PinkShnack commented
A really fun side-effect of having floating-point values in the image display is that we get a pinkish contour for the phase. :) I guess we have to fix this :')

![image](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/43960046/109f2afd-9a13-462c-a344-3a0263167a23)

2024-11-04 14:29 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
Phase is back!

Phase values are inverted here (as they are saved inverted in the example file).

![image](https://github.com/user-attachments/assets/7b56b13e-2ffc-47b6-80a5-03939d093205)

I will impement the `contour` utility methods that you mentioned above now. Contour looks a bit crazy right now!

With contours:
![image](https://github.com/user-attachments/assets/0e06c517-7869-482f-b55c-637be2c292e9)

2024-11-04 15:15 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
> Also, I believe there should be some way of setting the range for (at least) phase values. 

Do you envisage something like like:
![phase_range](https://github.com/user-attachments/assets/82cf076f-bd48-44ae-b8fe-47225faaf395)

Or on a per-image basis? For per image, we can use the built-in histogram. However, I don't like this.

2024-11-04 15:20 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +
Seems that the colorcet colormaps are now built-into pyqtgraph. https://github.com/pyqtgraph/pyqtgraph/blob/master/setup.py#L131

2024-11-04 15:20 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +
And I am not converting anymore FYI

2024-11-04 15:21 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +                    # just 2D images (not RGB)
This is a work in progress (probably going to follow your idea of having specific methods for contour handling).

2024-11-04 15:21 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +                if "qpi_pha" in ds:
> Maybe there should be a separate class entirely that handles image plotting? Generalization is not easy due to the different data types and requirements for visualization.

I think a simple method works for our use-case for image display. Could even make this into a method, seeing as we use it twice.

2024-11-07 10:33 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
Simply adding black as the contour colour for data with cmaps (phase) could be a simple solution.

![image](https://github.com/user-attachments/assets/676891d2-546b-4058-a135-b4cd0cf4e4e4)

2024-11-22 14:22 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
FYI, the colormap is centred at 0, as defined by the image levels (e.g. (-3.15, +3.15). I have confirmed this with some example data (below).

The events have phase values of roughly -3. The boxes are added for to show that pyqtgraph is spreading the data across the cmap range from our set levels value (-3.15, +3.15). The contour colour is set to black.

![image](https://github.com/user-attachments/assets/0c45ba47-2c44-4fec-898d-a4332fc94c80)

2024-11-22 14:24 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +                    # just 2D images (not RGB)
As I only had to add one `elif`, I think that we don't need to have extra methods for contour habdling:

```python
                if feat == "image" or feat == "qpi_amp":
                    cellimg[cont, 0] = int(
                        red_pix) if imkw["levels"][1] == 255 else red_pix
                    cellimg[cont, 1] = int(imkw["levels"][0])
                    cellimg[cont, 2] = int(imkw["levels"][0])
                elif feat == "qpi_pha":
                    # use the highest value from the colormap
                    cellimg[cont] = imkw["levels"][1]
```

2024-11-22 14:32 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +                if "qpi_pha" in ds:
I implemented this in `get_event_and_display`.

2024-11-22 14:40 UTC, PinkShnack commented
Hey @paulmueller I have added many of the changes we desired to have (except the user cannot yet set the phase range). I will now setup everything with pyqt6 and open a new PR. I hope the changes won't be much different...

But let's keep this open for now. Please feel free to comment.

2024-11-22 15:43 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
>              # axes combobox choices
I got an error when opening a (qpi) dataset. It said that I had to `set_dataset` first. This worked. Could be not how it was intended to be used though, seeing as it seems to work for you so far.

2024-11-22 15:44 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
>              self.comboBox_x.update_feature_list(default_choice="area_um")
I got an error when opening a (qpi) dataset. It said that I had to `set_dataset` first. This worked. Could be not how it was intended to be used though, seeing as it seems to work for you so far.

2024-11-26 12:28 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +    def display_contour(ds, event, state, cellimg):
Default should be +-pi

Auto contrast should be abs(+-min or max)

2024-11-28 15:43 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
>              self.comboBox_x.update_feature_list(default_choice="area_um")
This was due to me not merging something correctly.

2024-11-28 15:46 UTC, PinkShnack commented
Auto Contrast example (left without, right with):

![pha_autocontrast](https://github.com/user-attachments/assets/0feda543-1c07-4a17-8f72-314c3251539b)

2024-11-28 15:50 UTC, PinkShnack commented on pyproject.toml
> +py-modules = ['shapeout2']
This I needed to be able to run `pip install -e .`. Otherwise I get an error from pip complaining that I have multiple packages that could be built: `shapeout2`, `venv311` etc. Have you not gotten this error before?

2024-11-28 15:51 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +        self.levels_qpi_amp = (0, 2)
Required here as immutable objects because I need to access the defaults when changing the levels for phase and amplitude auto contrast.

2024-11-28 15:52 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +        elif feat == "qpi_pha":
This has gotten a bit messy. I will separate out the statements into functions. I can't see a way to do it smoothly, as each type of image feat needs a different order of processing.

2024-11-28 22:15 UTC, paulmueller commented on pyproject.toml
> +py-modules = ['shapeout2']
If you name your environment after something more common (e.g. ".env") or create it outside of the repository root, you should not encounter this problem (https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).

We can add this tool.setuptools though maybe using a separate PR?

2024-11-29 15:04 UTC, PinkShnack commented
FYI, for the test dataset, I downsclae the iFFT to half the original size. So for an imaging roi of 200x640, I have a `qpi_pha`, `qpi_amp`, `mask` etc of 100x320.

For that reason I get the following DCKIT check mismatch:

```
Compression: All
Data file format: hdf5
Fluorescence: False
Metadata: Mismatch [imaging] 'roi size x' and feature mask (640 vs 320)
Metadata: Mismatch [imaging] 'roi size y' and feature mask (200 vs 100)
```

I think this is okay. I think the smaller image size would also be better for the test dataset for storage purposes.

2024-11-29 15:06 UTC, PinkShnack commented
With DCKIT I also get this mismatch:

```
UnknownConfigurationKeyWarning: Unknown key 'filter size interpretation' in the 'qpi' section!
```

Somehow this keyword is not in dclab. This is the relevant section in `dclab/definitions/meta_const.py`:

```python
        # pipeline_kws
        ["filter name", str, "Fourier filter used"],
        # Corresponds to `filter_size_interpretation="frequency index"`
        ["filter size", float, "Fourier filter size [1/pix]"],
        ["scale to filter", fboolorfloat, "Scale QPI data to filter size"],
```

I think I was mistaken when I first added this when I said "# Corresponds to `filter_size_interpretation="frequency index"`".

We should add `filter size interpretation` as a QPI attr in dclab.

2024-12-02 09:33 UTC, paulmueller commented
> FYI, for the test dataset, I downsclae the iFFT to half the original size. So for an imaging roi of 200x640, I have a `qpi_pha`, `qpi_amp`, `mask` etc of 100x320.
> 
> For that reason I get the following DCKIT check mismatch:
> 
> ```
> Compression: All
> Data file format: hdf5
> Fluorescence: False
> Metadata: Mismatch [imaging] 'roi size x' and feature mask (640 vs 320)
> Metadata: Mismatch [imaging] 'roi size y' and feature mask (200 vs 100)
> ```
> 
> I think this is okay. I think the smaller image size would also be better for the test dataset for storage purposes.

For context: The hologram image is stored in the `qpi_oah` feature: https://github.com/DC-analysis/dclab/blob/0.62.6/dclab/definitions/feat_const.py#L168C7-L168C14

The check works against the `mask` feature: https://github.com/DC-analysis/dclab/blob/0.62.6/dclab/rtdc_dataset/check.py#L612

Since the hologram data are the absolute raw data, and x- and y-coordinates are only interesting in the downstream analysis, I would suggest to alter the ROI size in the metadata to match the processed QPI data. The original ROI size can be inferred from the `qpi` metadata section.

2024-12-02 09:35 UTC, paulmueller commented
> With DCKIT I also get this mismatch:
> 
> ```
> UnknownConfigurationKeyWarning: Unknown key 'filter size interpretation' in the 'qpi' section!
> ```
> 
> Somehow this keyword is not in dclab. This is the relevant section in `dclab/definitions/meta_const.py`:
> 
> ```python
>         # pipeline_kws
>         ["filter name", str, "Fourier filter used"],
>         # Corresponds to `filter_size_interpretation="frequency index"`
>         ["filter size", float, "Fourier filter size [1/pix]"],
>         ["scale to filter", fboolorfloat, "Scale QPI data to filter size"],
> ```
> 
> I think I was mistaken when I first added this when I said "# Corresponds to `filter_size_interpretation="frequency index"`".
> 
> We should add `filter size interpretation` as a QPI attr in dclab.

I believe we decided that the filter size interpretation is **always** going to be `"frequency index"`` for DC data **by definition**. Thus, you could simply stop writing `filter size interpretation` to the metadata.

2024-12-02 14:20 UTC, PinkShnack commented
> I believe we decided that the filter size interpretation is always going to be "frequency index" for DC data by definition. Thus, you could simply stop writing filter size interpretation to the metadata.

I have a vague recollection, but at no point did we write that down in the [original dclab PR](https://github.com/DC-analysis/dclab/pull/227), nor does it line up with qpretrieve where the [default value](https://github.com/RI-imaging/qpretrieve/blob/main/qpretrieve/interfere/base.py#L12) is "sideband distance"

2024-12-02 14:25 UTC, PinkShnack commented
> For context: The hologram image is stored in the qpi_oah feature: https://github.com/DC-analysis/dclab/blob/0.62.6/dclab/definitions/feat_const.py#L168C7-L168C14
> The check works against the mask feature: https://github.com/DC-analysis/dclab/blob/0.62.6/dclab/rtdc_dataset/check.py#L612
> Since the hologram data are the absolute raw data, and x- and y-coordinates are only interesting in the downstream analysis, I would suggest to alter the ROI size in the metadata to match the processed QPI data. The original ROI size can be inferred from the qpi metadata section.

Aha good spot, I've just been using `image` and `qpi_oah` interchangably in my pipeline because it makes things easy. In fact, I have them as linked hdf5 datasets. I'll clean that up. 

Side note, but was github's comment system always this clunky?

2024-12-02 14:48 UTC, PinkShnack commented
Regarding the test file size. I have one with 10 events and it is 2.5 MB. I actually tried to compress with clevel=22 in dclab, but it doesn't seem to work. But that's beside the point. Is 2.5 MB reasonable, or too big? It's those darn float32 images :)

2024-12-02 15:08 UTC, PinkShnack commented on shapeout2/gui/quick_view/qv_main.py
> +        elif feat == "qpi_pha":
I organised the `get_event_image` method into `display_image` for the image pixel information processing and `display_contour` for the contour overlay.

2024-12-02 17:18 UTC, PinkShnack commented on tests/test_gui_quickview.py
> +    assert not np.sum(np.isin(image_without_contour, lowest_cmap_val))  # == 1
I have set this as xfail for now to illustrate the issue with how I am displaying the contour on the phase data.

I basically have a 2d image and display it with a cmap (like coolwarm). However, to display a contour with this cmap, we have to have one of the cmap colours represent the contour. I have chosen to represent the contour with black and by setting the first entry in the cmap to black. However, this means that we have a black pixel randomly in our event image when we use auto-contrast.

Perhaps there is a smarter way to display the contour. Ah, I could plot it as RGB  and set the alpha to 1 for the contour pixels...

2024-12-03 08:31 UTC, paulmueller commented
> > I believe we decided that the filter size interpretation is always going to be "frequency index" for DC data by definition. Thus, you could simply stop writing filter size interpretation to the metadata.
> 
> I have a vague recollection, but at no point did we write that down in the [original dclab PR](https://github.com/DC-analysis/dclab/pull/227), nor does it line up with qpretrieve where the [default value](https://github.com/RI-imaging/qpretrieve/blob/main/qpretrieve/interfere/base.py#L12) is "sideband distance"

Yes, we might have discussed that in person. The default in qpretrieve is for user convenience. Here, in dclab, we can work with quantitative and exact frequency values. I believe this is fine and does not cause any problems. The docs could be updated though. The one line `Corresponds to filter_size_interpretation="frequency index"` is not extremely informative.

2024-12-03 08:32 UTC, paulmueller commented
> Regarding the test file size. I have one with 10 events and it is 2.5 MB. I actually tried to compress with clevel=22 in dclab, but it doesn't seem to work. But that's beside the point. Is 2.5 MB reasonable, or too big? It's those darn float32 images :)

Have you tried rounding the float32 images to the 2nd or 3rd digit before saving? Then compression would be more efficient.

2024-12-03 08:35 UTC, paulmueller commented on tests/test_gui_quickview.py
> +    assert not np.sum(np.isin(image_without_contour, lowest_cmap_val))  # == 1
pyqtgraph might have the option to draw two images on top of each other (with the top one being mostly transparent)

2024-12-03 14:56 UTC, PinkShnack commented on tests/test_gui_quickview.py
> +    assert not np.sum(np.isin(image_without_contour, lowest_cmap_val))  # == 1
I figured this out btw. 
- Display with contour: Change the first colour in the cmap to black.
   - With auto-contrast, add an extra datapoint "level" so that the lowest value is no longer black, but the next colour up (darkest blue from coolwarm). This datapoint level I call an offset in the code.
   - Without auto-contrast, this may be a problem. Might add the offset here also.

2024-12-03 15:43 UTC, PinkShnack commented
> > > I believe we decided that the filter size interpretation is always going to be "frequency index" for DC data by definition. Thus, you could simply stop writing filter size interpretation to the metadata.
> > 
> > 
> > I have a vague recollection, but at no point did we write that down in the [original dclab PR](https://github.com/DC-analysis/dclab/pull/227), nor does it line up with qpretrieve where the [default value](https://github.com/RI-imaging/qpretrieve/blob/main/qpretrieve/interfere/base.py#L12) is "sideband distance"
> 
> Yes, we might have discussed that in person. The default in qpretrieve is for user convenience. Here, in dclab, we can work with quantitative and exact frequency values. I believe this is fine and does not cause any problems. The docs could be updated though. The one line `Corresponds to filter_size_interpretation="frequency index"` is not extremely informative.

I created an issue over at dclab here: https://github.com/DC-analysis/dclab/issues/267

2024-12-03 15:43 UTC, PinkShnack commented
> > Regarding the test file size. I have one with 10 events and it is 2.5 MB. I actually tried to compress with clevel=22 in dclab, but it doesn't seem to work. But that's beside the point. Is 2.5 MB reasonable, or too big? It's those darn float32 images :)
> 
> Have you tried rounding the float32 images to the 2nd or 3rd digit before saving? Then compression would be more efficient.

Yes, the file is now 1.4 MB. Thanks for the tip.

2024-12-03 15:45 UTC, PinkShnack commented on pyproject.toml
> +py-modules = ['shapeout2']
We can discuss this elsewhere, but "venvXXX" is quite common. "venv" is the default in pycharm afaik.

2024-12-03 15:50 UTC, PinkShnack commented on pyproject.toml
> +py-modules = ['shapeout2']
#181

2024-12-03 16:20 UTC, PinkShnack commented
Example for the QPI.

![QPI_example](https://github.com/user-attachments/assets/3af9f6de-d298-411b-89a7-d17b3e246c25)

If you could, please have a look at the branch. The Polygon page image stretching isn't as nice as with the Event page.

2024-12-05 10:04 UTC, PinkShnack commented
The other "todo" now is to add some documentation perhaps. What do you think?

2024-12-12 13:29 UTC, paulmueller requested changes

2024-12-12 13:29 UTC, paulmueller commented on CHANGELOG
> + - feat: display and handle quantitative phase imaging data
Version 2.19.1 is already released.
Please create a new minor release "2.20.0" (because you added a feature)

2024-12-12 13:29 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +        v_largest = (vmax_abs if vmax_abs >= vmin_abs else vmin_abs)
replace with `max(vmax_abs, vmin_abs)`

2024-12-12 13:29 UTC, paulmueller commented on tests/data/blood_rbc_qpi_data.rtdc
please upload new file

2024-12-13 10:30 UTC, merged