Enable LUT selection for emodulus computation in analysis view
DC-analysis/DCscope pull request #166
Opened 2024-09-20 12:38 UTC by RaghavaAlajangi

This PR aims to implement the selection of LUT in the analysis view. This is mentioned as a second point in the issue #71.

2024-09-20 12:41 UTC, RaghavaAlajangi commented on shapeout2/gui/analysis/ana_slot.py
> +        self.comboBox_lut.setVisible(medium_key.count("MC-PBS"))
I don't know whether we need this. I just followed the `comboBox_visc_model` implementation.

2024-09-20 12:42 UTC, RaghavaAlajangi commented
Hi @paulmueller 
please take a look at these changes when you have time.

2024-09-23 06:07 UTC, paulmueller commented on shapeout2/gui/analysis/ana_slot.py
> +        idx_lut = self.comboBox_lut.findText(emodulus.get("emodulus lut", ""))
Just a comment: For now, this is fine, because it follows the current code. But in general, using `Data` instead of `Text` is cleaner, because text might be subject to internationalization: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/issues/167

2024-09-23 06:15 UTC, paulmueller requested changes

2024-09-23 06:15 UTC, paulmueller commented on shapeout2/gui/analysis/ana_slot.py
> +        self.comboBox_lut.setVisible(medium_key.count("MC-PBS"))
The viscosity model is only applicable for MC-PBS, whereas the LUT selection is universal. So no, we must not hide the LUT selection if the buffer is set to MC-PBS.

2024-09-23 07:31 UTC, RaghavaAlajangi commented on shapeout2/gui/analysis/ana_slot.py
> +        self.comboBox_lut.setVisible(medium_key.count("MC-PBS"))
Thanks for letting me know.

2024-09-23 07:57 UTC, RaghavaAlajangi commented
Hi @paulmueller ,
I have made the changes that are asked for. Please have a look.

2024-09-24 07:44 UTC, paulmueller approved these changes

2024-09-24 07:45 UTC, merged