Enable lut selection for isoelasticity lines
DC-analysis/DCscope pull request #170
Opened 2024-10-04 13:31 UTC by RaghavaAlajangi

This PR aims to implement the selection of LUT in the quick view to plot different isoelasticity lines. This is mentioned as a fourth point in the issue #71 .

2024-10-04 13:36 UTC, RaghavaAlajangi commented
Hi Paul,
as I mentioned, I pushed the changes. Please review the code and let me know if it needs any changes.

2024-10-04 13:57 UTC, paulmueller requested changes
Thanks, looks good to me in general, only one minor change.
Please make sure `flake8` passes (CI is failing).

2024-10-04 13:57 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +        self.update_lut_choices()
This function is intended to only be run once during init. Since the remainder of the initialization of all widgets is done during init, I would prefer if you could put the code of the function here instead.

2024-10-04 13:57 UTC, paulmueller commented on shapeout2/gui/quick_view/qv_main.py
> +        self.update_lut_choices()
Note that the term `update` is also misleading. There is another method `update_polygon_panel`, which is also called after initialization (and this is fine).

2024-10-04 14:14 UTC, RaghavaAlajangi commented on shapeout2/gui/quick_view/qv_main.py
> +        self.update_lut_choices()
I put the code in the constructor itself.

2024-10-08 07:07 UTC, RaghavaAlajangi commented
Hi Paul,
does it need any other changes? could you take a look at it?

2024-10-08 07:39 UTC, paulmueller approved these changes

2024-10-08 07:40 UTC, merged